package nc.instrumentum.recordatormunerum.model;

import java.util.Calendar;

public class Registratio {

    // Id latter autogenerated.
    private int id;
    // Title.
    private String title;
    // Daily selector.
    private String weekDays;    //0 -> No days, 1..7 selected days, 8 -> all days.
    // Weekly selector.
    private int repeatEveryWeeks;  // 0 -> No weeks, 1 -> everyweek, 2 -> separated weeks, 3 -> every 3 weeks.
    // Annual selector
    private String monthDays;  // 0 -> No days, 1..31 -> selected days, 32 -> all days.
    private String yearMonths;  //0 -> No months, 1..12 -> selected months, 13 -> all months.
    private String monthlyPattern;  // FIRST_MONDAY, SECOND_WEDNESDAY, THIRD_SATURDAY, LAST_SUNDAY...
    // Daily time
    private int hour;
    private int minute;
    // In use indicator.
    private boolean active;
    // Start and limit.
    private long startDateMillis;   // base of patron.
    private Long endDateMillis;     // null = undefined.

    //Constructor

    public Registratio() {
    }

    public Registratio(int di, String ie, String eea, int oee, String oa, String eao, String oae, int ou, int iue, boolean aie, long start, Long end) {

        this.id = di;

        this.title = ie;

        this.weekDays = eea;

        this.repeatEveryWeeks = oee;

        this.monthDays = oa;

        this.yearMonths = eao;

        this.monthlyPattern = oae;

        this.hour = ou;

        this.minute = iue;

        this.active = aie;

        this.startDateMillis = start;

        this.endDateMillis = end;
    }

    //Getters and Setters

    public int getId() {
        return id;
    }

    public void setId(int ids) {
        this.id = ids;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String ttl) {
        this.title = ttl;
    }

    public String getWeekDays() {
        return weekDays;
    }

    public void setWeekDays(String wkDys) {
        this.weekDays = wkDys;
    }

    public int getRepeatEveryWeeks() {
        return repeatEveryWeeks;
    }

    public void setRepeatEveryWeeks(int rew) {
        this.repeatEveryWeeks = rew;
    }

    public String getMonthDays() {
        return monthDays;
    }

    public void setMonthDays(String mnthsDys) {
        this.monthDays = mnthsDys;
    }

    public String getYearMonths() {
        return yearMonths;
    }

    public void setYearMonths(String yrMnths) {
        this.yearMonths = yrMnths;
    }

    public String getMonthlyPattern() {
        return this.monthlyPattern;
    }

    public void setMonthlyPattern(String mnthlPttrn) {
        this.monthlyPattern = mnthlPttrn;
    }

    public int getHour() {
        return hour;
    }

    public void setHour(int h) {
        this.hour = h;
    }

    public int getMinute() {
        return minute;
    }

    public void setMinute(int min) {
        this.minute = min;
    }

    public boolean getActive() {
        return active;
    }

    public void setActive(boolean activo) {
        this.active = activo;
    }

    public long getStartDateMillis() {
        return startDateMillis;
    }

    public void setStartDateMillis(long strtDtMlls) {
        this.startDateMillis = strtDtMlls;
    }

    public Long getEndDateMillis() {
        return endDateMillis;
    }

    public void setEndDateMillis(Long ndDtMlls) {
        this.endDateMillis = ndDtMlls;
    }

    public Registratio getAll() {
        Registratio aux = new Registratio(this.id, this.title, this.weekDays, this.repeatEveryWeeks, this.monthDays, this.yearMonths,
                this.monthlyPattern, this.hour, this.minute, this.active, this.startDateMillis, this.endDateMillis);

        return aux;
    }

    public long getNextTriggerMillis() {

        Calendar now = Calendar.getInstance();
        Calendar next = Calendar.getInstance();

        // Base: hoy a la hora configurada
        next.set(Calendar.HOUR_OF_DAY, hour);
        next.set(Calendar.MINUTE, minute);
        next.set(Calendar.SECOND, 0);
        next.set(Calendar.MILLISECOND, 0);

        // Si está antes de la fecha de inicio, saltamos al startDate
        if (next.getTimeInMillis() < startDateMillis) {
            next.setTimeInMillis(startDateMillis);
            next.set(Calendar.HOUR_OF_DAY, hour);
            next.set(Calendar.MINUTE, minute);
        }

        // Si ya ha pasado hoy, programamos mañana
        if (next.getTimeInMillis() <= now.getTimeInMillis()) {
            next.add(Calendar.DAY_OF_YEAR, 1);
        }

        return next.getTimeInMillis();
    }
}
